server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    #是否将当前的eureka服务作为客户端进行注册
    register-with-eureka: false
    #是否同步其他eureka注册中心的数据
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka/
